[context.prod.environment]
    REACT_APP_APPLICATION_NAME = "Talisman"
    REACT_APP_RAMP_API_KEY = "auu2eae53pvp6pboq7oft9dxh5fznhwq7h6tpaxq"

[context.staging.environment]
    REACT_APP_APPLICATION_NAME = "Talisman Staging"
    REACT_APP_RAMP_API_KEY = "y3asdf899w5xcnxguzas93uwg86dcxz54xaogyt9"
    REACT_APP_RAMP_URL = "https://ri-widget-staging.firebaseapp.com"

[context.deploy-preview.environment]
    REACT_APP_APPLICATION_NAME = "Talisman PR Preview"
    REACT_APP_RAMP_API_KEY = "y3asdf899w5xcnxguzas93uwg86dcxz54xaogyt9"
    REACT_APP_RAMP_URL = "https://ri-widget-staging.firebaseapp.com"
